title: "Yajuan Lin"
author: "Yajuan Lin"
description: "Contact Yajuan

Email: linyajuan@gmail.com

PhD student positions available. If you are interested in joining our lab, contact the PI for opportunities. "
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Home", file: "index.html"}
  - {title: "People", file: "README.md"}
  - {title: "Publications", file: "Publications.md"}
  - {title: "CV", file: "yajuanlin.pdf"}

# external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
#  - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
#  - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}
#  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
